#hackinvest.dvi : hackinvest.ltx
#	latex hackinvest.ltx

#hackinvest.pdf : hackinvest.ltx
#	pdflatex hackinvest.ltx

clean :
	rm -f hackinvest.aux hackinvest.dvi 
	rm -f hackinvest.glg hackinvest.glo hackinvest.gls
	rm -f hackinvest.idx hackinvest.ilg hackinvest.ind hackinvest.ist
	rm -f hackinvest.log hackinvest.lot hackinvest.toc

